name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  
  # DI
  get_it: ^8.0.3
  
  # Navigation
  go_router: ^14.7.1
  
  # Localization
  toln: ^0.0.3
  
  # Serialization
  json_annotation: ^4.9.0
  
  # UI & Animations
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  toastification: ^2.3.0
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  fl_chart: ^1.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locales/

dependency_overrides:
  analyzer: ^9.0.0
  test_api: 0.7.7
  matcher: 0.12.17